services:
  gosend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - PORT=8080
    volumes:
      - gosenddata:/app/data
    restart: unless-stopped
    networks:
      - caddynet

networks:
  caddynet:
    external: true

volumes:
  gosenddata:
    external: true
