services:
  gosend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "8080"
    environment:
      - PORT=8080
    volumes:
      - gosenddatav2:/app/data
    restart: unless-stopped
    networks:
      - caddynet

networks:
  caddynet:
    external: true

volumes:
  gosenddatav2:
    external: true
